name: 123Testing
favicon: null
layout_spectrum: 0.7028550475370139
typography_spectrum: 0.23012048727832735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.13849057257175446
  lightness: 0.6694565834477544
  saturation: 0.8774950439110398
  rhythmicContrast: 0.5099431085400283
purpose: []
